### ISSUE TITLE
Shouldn't "Login or Sign In to comment" be "Login or Register to comment"?

### ISSUE THREAD

**Issue by stanleyjones** [strategio/wpsidecomments#2]
Line 298 on https://github.com/strategio/wpsidecomments/blob/master/public/class-wp-side-comments.php

```
'logInOrSignInToComment' => __('Login or Register to comment', $this->plugin_slug),
```

Unless I'm missing the distinction...

**Comment by strategio** [comment]
Thank for your comment @stanleyjones 
I commited the new translation 3a0ac22d2eaf8cfbc6c28198d2641e8510855a0a

**Comment by stanleyjones** [comment]
Thanks!
